Update Dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -62,15 +62,15 @@ RUN set -ox pipefail \
         echo "build-arg VERSION is required" \
         && exit 1; \
     fi \
-    && if [[ "${SHA256}" == "" ]]; then \
-        echo "build-arg SHA256 is required" \
-        && exit 1; \
-    fi \
+    # && if [[ "${SHA256}" == "" ]]; then \
+    #     echo "build-arg SHA256 is required" \
+    #     && exit 1; \
+    # fi \
     && archive="/tmp/factorio_headless_x64_$VERSION.tar.xz" \
     && mkdir -p /opt /factorio \
     && curl -sSL "https://www.factorio.com/get-download/$VERSION/headless/linux64" -o "$archive" --retry $CURL_RETRIES \
-    && echo "$SHA256  $archive" | sha256sum -c \
-    || (sha256sum "$archive" && file "$archive" && exit 1) \
+    # && echo "$SHA256  $archive" | sha256sum -c \
+    # || (sha256sum "$archive" && file "$archive" && exit 1) \
     && tar xf "$archive" --directory /opt \
     && chmod ugo=rwx /opt/factorio \
     && rm "$archive" \
